name: Scheduled Monitor

on:
  schedule:
    - cron: '*/5 0-8 * * *' # Runs every 5 minutes from 00:00 to 08:55 UTC (09:00–17:55 JST)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TARGET_URL: ${{ secrets.TARGET_URL }}
      MOBILE_URL: ${{ secrets.MOBILE_URL }}
      KEYWORD: ${{ secrets.KEYWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync

      - name: Install Playwright browsers
        run: uv run playwright install chromium
        
      - name: Run the project
        run: uv run main.py

